[logger]
level = "warning"

[client]
showSidebarNavigation = true
showErrorDetails = false
toolbarMode = "viewer"

[server]
headless = true
runOnSave = false
address = "0.0.0.0"
port = 8501
maxUploadSize = 200
maxMessageSize = 200
enableXsrfProtection = true
fileWatcherType = "none"
folderWatchBlacklist = ['01_Data', '02_Notebooks', '__pycache__', '.git', '.vscode']

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
base = "light"
primaryColor = "#13315c"
backgroundColor = "#f4f7fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"
